Лабораторная работа 2
krivenkovadd/Laboratirniye pull request #2
Opened 2024-10-29 10:16 UTC by krivenkovadd

2024-10-31 14:45 UTC, rmushkin requested changes
Есть замечание по округлению, пожалуйста, исправьте.

2024-10-31 14:45 UTC, rmushkin commented on Лабораторная работа 2/Продолжение финансового планирования.py
> +money_capital = round(money_capital)
Ловушка с `round`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-31 19:34 UTC, krivenkovadd reviewed
Исправление недочетов.

2024-11-01 19:32 UTC, rmushkin approved these changes
Принимается ✅

2024-11-01 19:32 UTC, merged