Add files via upload
krivenkovadd/Laboratirniye pull request #3
Opened 2024-11-03 15:37 UTC by krivenkovadd

2024-11-07 21:10 UTC, rmushkin requested changes
Всё прекрасно, но вы упорно не хотите настраивать автоформатировщик. Иначе бы новыйе строки в конце автоматически подобавлялись бы...

2024-11-07 21:10 UTC, rmushkin commented on Лабораторная работа 3/Поиск общих участников.py
> +print(find_common_participants(participants_first_group,participants_second_group, sep = '|'))
PEP8

2024-11-07 21:10 UTC, rmushkin commented on Лабораторная работа 3/Поиск общих участников.py
> +def find_common_participants(participants_first_group, participants_second_group, sep = ','):
PEP8

2024-11-07 21:10 UTC, rmushkin commented on Лабораторная работа 3/Частотный анализ в тексте.py
> +    print(f"{letter}: {frequency:.2f}")
Новая... строка... в конце... файла...

2024-11-07 21:39 UTC, krivenkovadd reviewed
Исполнение правок

2024-11-08 16:15 UTC, rmushkin approved these changes
Принимается ✅

2024-11-08 16:15 UTC, merged